#include "pch.h"
#include "MP3CodecFactory.h"
#include "PlatformHelpers.h"

#include <limits>
#include <cassert>
#include <libhelpers/HSystem.h>

Microsoft::WRL::ComPtr<IMFTransform> MP3CodecFactory::CreateIMFTransform() {
    return PlatformHelpers::CreateTransform(L".mp3",
        [](uint32_t i, uint32_t numChannels, uint32_t sampleRate, uint32_t bitsPerSample)
    {
        return MP3CodecFactory::CreateOutType(i, numChannels, sampleRate, bitsPerSample);
    });
}

Microsoft::WRL::ComPtr<IMFMediaType> MP3CodecFactory::CreateOutType(
    uint32_t typeIndex,
    uint32_t numChannels,
    uint32_t sampleRate,
    uint32_t /*bitsPerSample*/)
{
    if (typeIndex >= 2) {
        return nullptr;
    }

    HRESULT hr = S_OK;
    Microsoft::WRL::ComPtr<IMFMediaType> type;
    const uint32_t bitrate = 128000;

    hr = MFCreateMediaType(type.GetAddressOf());
    H::System::ThrowIfFailed(hr);

    hr = type->SetGUID(MF_MT_MAJOR_TYPE, MFMediaType_Audio);
    H::System::ThrowIfFailed(hr);

    hr = type->SetGUID(MF_MT_SUBTYPE, MFAudioFormat_MP3);
    H::System::ThrowIfFailed(hr);

    hr = type->SetUINT32(MF_MT_AUDIO_NUM_CHANNELS, numChannels);
    H::System::ThrowIfFailed(hr);

    hr = type->SetUINT32(MF_MT_AUDIO_SAMPLES_PER_SECOND, sampleRate);
    H::System::ThrowIfFailed(hr);

    hr = type->SetUINT32(MF_MT_AUDIO_AVG_BYTES_PER_SECOND, bitrate / 8);
    H::System::ThrowIfFailed(hr);

    hr = type->SetUINT32(MF_MT_AUDIO_BLOCK_ALIGNMENT, 1);
    H::System::ThrowIfFailed(hr);

    if (typeIndex >= 1) {
        MPEGLAYER3WAVEFORMAT mp3wavefmt = {};

        hr = type->SetUINT32(MF_MT_AUDIO_PREFER_WAVEFORMATEX, TRUE);
        H::System::ThrowIfFailed(hr);

        mp3wavefmt.wID = MPEGLAYER3_ID_MPEG;
        mp3wavefmt.fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF;
        mp3wavefmt.nFramesPerBlock = 1;
        mp3wavefmt.nCodecDelay = 0;

        bool mpeg1 = sampleRate == 32000 || sampleRate == 44100 || sampleRate == 48000;
        bool mpeg2 = sampleRate == 16000 || sampleRate == 22050 || sampleRate == 24000;
        bool mpeg25 = sampleRate == 8000 || sampleRate == 11025 || sampleRate == 12000;

        /*
        http://masm32.com/board/index.php?topic=2841.0
        For MPEG layer-3,

        block size  MPEG 1 == 1152
        block size  MPEG 2 & 2.5 == 576

        frame size: ((block size / 8 * bitrate * 1000) / samplerate) + padding size

        total mp3 file duration in milliseconds: file length / average bitrate / 8
        */

        // https://docs.microsoft.com/en-us/windows/desktop/medfound/mp3-audio-encoder
        // https://en.wikipedia.org/wiki/MP3

        if (mpeg1) {
            // 1152 / 8 = 144
            uint32_t blockSize = 144 * bitrate / sampleRate;

            if (blockSize > (std::numeric_limits<WORD>::max)()) {
                // check logic
                assert(false);
                H::System::ThrowIfFailed(E_FAIL);
            }

            mp3wavefmt.nBlockSize = (WORD)blockSize;
        }
        else if(mpeg2 || mpeg25) {
            // 576 / 8 = 72
            uint32_t blockSize = 72 * bitrate / sampleRate;

            if (blockSize > (std::numeric_limits<WORD>::max)()) {
                // check logic
                assert(false);
                H::System::ThrowIfFailed(E_FAIL);
            }

            mp3wavefmt.nBlockSize = (WORD)blockSize;
        }
        else {
            // check logic
            assert(false);
            H::System::ThrowIfFailed(E_FAIL);
        }

        const auto userDataExpectedSize = (sizeof MPEGLAYER3WAVEFORMAT - sizeof WAVEFORMATEX);
        const auto userDataOffset = sizeof WAVEFORMATEX;

        uint8_t *bytes = reinterpret_cast<uint8_t*>(&mp3wavefmt);
        bytes += userDataOffset;

        hr = type->SetBlob(MF_MT_USER_DATA, bytes, userDataExpectedSize);
        H::System::ThrowIfFailed(hr);
    }

    return type;
}

// valid types from desktop MFTEnum:
/*
0 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 40000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 1440; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

1 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 40000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 1044; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

2 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 40000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 960; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

3 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 32000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 1152; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

4 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 32000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 835; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

5 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 32000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 768; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

6 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 28000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 1008; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

7 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 28000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 731; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

8 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 28000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 672; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

9 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 24000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 864; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

10 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 24000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 626; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

11 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 24000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 576; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

12 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 20000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 720; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

13 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 20000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 522; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

14 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 20000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 480; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

15 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 16000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 576; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

16 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 16000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 417; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

17 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 16000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 384; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

18 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 14000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 504; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

19 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 14000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 365; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

20 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 14000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 336; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

21 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 12000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 432; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

22 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 12000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 313; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

23 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 12000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 288; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

24 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 10000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 16000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 360; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

25 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 10000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 22050
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 261; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

26 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 10000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 24000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 240; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

27 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 8000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 16000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 288; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

28 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 8000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 22050
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 208; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

29 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 8000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 24000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 192; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

30 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 7000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 16000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 252; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

31 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 7000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 22050
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 182; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

32 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 7000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 24000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 168; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

33 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 6000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 16000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 216; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

34 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 6000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 22050
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 156; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

35 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 6000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 24000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 144; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

36 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 5000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 16000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 180; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

37 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 5000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 22050
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 130; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

38 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 5000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 24000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 120; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

39 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 4000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 8000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 288; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

40 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 4000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 11025
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 208; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

41 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 4000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 12000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 192; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

42 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 4000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 16000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 144; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

43 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 4000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 22050
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 104; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

44 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 4000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 24000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 96; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

45 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 3000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 8000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 216; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

46 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 3000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 11025
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 156; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

47 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 3000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 12000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 144; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

48 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2500
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 8000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 360; nFramesPerBlock = 2; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

49 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2500
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 11025
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 260; nFramesPerBlock = 2; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

50 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2500
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 12000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 240; nFramesPerBlock = 2; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

51 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2250
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 8000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 648; nFramesPerBlock = 4; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

52 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2250
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 11025
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 468; nFramesPerBlock = 4; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

53 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2250
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 2
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 12000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 432; nFramesPerBlock = 4; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

54 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 16000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 576; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

55 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 16000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 417; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

56 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 16000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 384; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

57 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 14000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 504; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

58 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 14000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 365; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

59 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 14000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 336; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

60 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 12000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 432; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

61 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 12000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 313; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

62 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 12000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 288; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

63 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 10000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 360; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

64 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 10000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 261; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

65 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 10000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 240; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

66 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 8000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 288; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

67 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 8000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 208; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

68 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 8000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 192; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

69 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 7000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 252; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

70 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 7000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 182; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

71 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 7000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 168; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

72 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 6000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 16000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 216; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

73 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 6000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 22050
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 156; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

74 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 6000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 24000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 144; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

75 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 6000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 32000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 216; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

76 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 6000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 44100
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 156; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

77 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 6000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 48000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 144; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

78 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 5000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 16000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 180; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

79 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 5000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 22050
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 130; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

80 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 5000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 24000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 120; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

81 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 4000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 16000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 144; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

82 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 4000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 22050
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 104; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

83 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 4000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 24000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 96; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

84 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 3000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 16000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 108; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

85 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 3000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 22050
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 78; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

86 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 3000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 24000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 72; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

87 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2500
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 11025
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 260; nFramesPerBlock = 2; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

88 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2500
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 12000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 240; nFramesPerBlock = 2; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

89 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2500
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 16000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 180; nFramesPerBlock = 2; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

90 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2250
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 11025
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 468; nFramesPerBlock = 4; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

91 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2250
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 12000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 432; nFramesPerBlock = 4; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

92 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2250
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 16000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 324; nFramesPerBlock = 4; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

93 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 8000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 144; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

94 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 11025
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 104; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

95 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 12000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 96; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

96 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 2000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 16000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 72; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

97 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 1000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 8000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 72; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

98 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 1000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 11025
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 52; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3

99 :
    MF_MT_AUDIO_AVG_BYTES_PER_SECOND = 1000
    MF_MT_AUDIO_BLOCK_ALIGNMENT = 1
    MF_MT_AUDIO_NUM_CHANNELS = 1
    MF_MT_MAJOR_TYPE = MFMediaType_Audio
    MF_MT_AUDIO_SAMPLES_PER_SECOND = 12000
    MF_MT_AUDIO_PREFER_WAVEFORMATEX = 1
    MF_MT_USER_DATA = wID = MPEGLAYER3_ID_MPEG; fdwFlags = MPEGLAYER3_FLAG_PADDING_OFF; nBlockSize = 48; nFramesPerBlock = 1; nCodecDelay = 0;
    MF_MT_SUBTYPE = MFAudioFormat_MP3
*/