#pragma once
#include <wrl.h>
#include <d2d1.h>
#include <d2d1_1.h>
#include <d2d1_2.h>
#include <d2d1_3.h>
#include <d2d1effects_2.h>
#include <d3d11.h>
#include <d3d11_1.h>
#include <d3d11_2.h>
#include <d3d11_3.h>
#include <dxgi1_4.h>
#include <dxgi1_5.h>
#include <dxgi1_6.h>
#include <dwrite.h>
#include <dwrite_3.h>
#include <wincodec.h>
#include <DirectXMath.h>
#include <DirectXColors.h>