<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<NugetName>CrashHandling</NugetName>
	</PropertyGroup>
	
	<ItemDefinitionGroup>
		<ClCompile>
			<AdditionalIncludeDirectories>
				%(AdditionalIncludeDirectories);
				$(ProjectDir)
			</AdditionalIncludeDirectories>
			<PreprocessorDefinitions>
				<!--DISABLE_ERROR_LOGGING;
        DISABLE_COMMON_LOGGING;
        DISABLE_VERBOSE_LOGGING;
        DISABLE_CLASS_FULLNAME_LOGGING;-->
				
				<!-- Redefine public namespace macros, but aliases must be original -->
				CRASH_HANDLING_NUGET_HELPERS_NS=__$(NugetName)H_ns;
				CRASH_HANDLING_NUGET_MEDIA_FOUNDATION_NS=__$(NugetName)MF_ns;
				HELPERS_NS=CRASH_HANDLING_NUGET_HELPERS_NS;
				MEDIA_FOUNDATION_NS=CRASH_HANDLING_NUGET_MEDIA_FOUNDATION_NS;
				%(PreprocessorDefinitions)
			</PreprocessorDefinitions>
		</ClCompile>
	</ItemDefinitionGroup>
</Project>